class Ball{
    constructor(x,y,radius,vX=0,vY=0,type='normal'){
        if(!(balls.length>5)){balls.push(this)
        this.sprite=new Sprite(x,y,radius)
        this.sprite.vel.x=vX
        this.sprite.vel.y=vY
        this.type=type
        this.id=undefined
        let ids=[]
        balls.forEach(ball=>{
            ids.push(ball.id)
        })
        let tempId=1
        for(tempId;ids.includes(tempId);tempId=Math.floor(random(1,1001))){/*Do nothing*/}
        this.id=tempId
        this.sprite.bounciness=1
        this.rad=radius
        this.orig={x:x,y:y}
        this.a=255
        balls.forEach(ball=>{
                this.sprite.overlaps(ball.sprite)
        })
        if(type=='normal'){
            this.sprite.color=255
        }else if(type=='explosive'){
            this.sprite.color='orange'
            edges.forEach(edge=>{
                this.sprite.overlaps(edge)
            })
        }
        modifiers.forEach(mod => {
            this.sprite.overlaps(mod.sprite)
        });
        this.state='normal'
        this.origPos=undefined}
    }
    draw(){
        if(this.sprite.vel.x==0&&this.type!='explosive'){
            this.sprite.vel.x+=random(-1,1)
        }
        if(this.sprite.vel.y==0){
            this.sprite.vel.y+=random(-1,1)
        }
        if(this.removed==true){
            this.sprite.remove()
            balls.splice(balls.indexOf(this),1)
        }
        if(gameState==0){
            this.sprite.x=paddle.sprite.x
            this.sprite.y=this.orig.y
        }
        if(this.sprite.y>height+this.rad/2){
            this.removed=true
        }
        if(this.sprite.collides(edges)||this.sprite.collides(paddle.sprite)){
            let temp=random(sounds.ball_hit)
            temp.play()
        }
        if(this.type=='explosive'){
            edges.forEach(edge=>{
                if(this.sprite.overlaps(edge)){
                    setTimeout(()=>{this.removed=true},150)
                }
            })
        }
        if(this.state=='exploding'){
            this.sprite.radius<10000/height?this.sprite.radius+=3000/height:this.state='decaying'
            this.sprite.x=this.origPos[0]
            this.sprite.y=this.origPos[1]
        }
        if(this.state=='decaying'){
            if(this.a>0){
                this.a-=25
                this.sprite.color=color(255,165,0,this.a)
                this.sprite.x=this.origPos[0]
                this.sprite.y=this.origPos[1]
            }else{
                this.removed=true
                this.state='removing'
            }
        }
        /*fill(255)
        text(this.id,this.sprite.x,this.sprite.y+this.rad/2,15)*/
    }
    start(){
        this.sprite.direction=random(-125,-45)
        this.sprite.speed=longSide/200
    }
    explode(orig){
        this.type='explotion'
        this.state='exploding'
        this.origPos=[orig.x,orig.y]
    }
}